spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: certifistoragedinesh
          account-key: ***
          endpoint: DefaultEndpointsProtocol=https;AccountName=certifistoragedinesh;AccountKey=***==;EndpointSuffix=core.windows.net